builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1

stages:
  build:
    image: golang:1.14.2-alpine3.11
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOGC: off
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    inline: |
      FROM scratch

      LABEL maintainer="estafette.io" \
            description="The ${ESTAFETTE_GIT_NAME} is the component that handles api requests and starts build jobs using the estafette-ci-builder"

      COPY ca-certificates.crt /etc/ssl/certs/
      COPY ${ESTAFETTE_GIT_NAME} /

      ENV GRACEFUL_SHUTDOWN_DELAY_SECONDS="20"

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - estafette
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  tooling:
    actions:
    - name: deploy-canary
    - name: deploy-stable
    - name: rollback-canary
    clone: true
    stages:
      deploy:
        image: extensions/gke:dev
        namespace: estafette
        visibility: iap
        iapOauthClientID: estafette.secret(xEufMLLIWhF-dd_K.HnmSC97N6e04cv_6e-2Gl83xSKIXEmFsZmCYhq1lPr9EOV7sFwroy0l4X2KXlIpIS309GR9i0M8UPDJA3b2vplXyDv8sia_SGecBOV-5oemhHE0UIxL3z_bhvnplDe0ioplMaPfNPb-b7S_D2uoN04t37hk=.NESnG-bFhvcZZbvmRc2EwOX8DPZaRVxwSXyrm5RXSbNJQHnoM2VVGGMK4UfTjOKOvdpum-E=)
        iapOauthClientSecret: estafette.secret(KhumCII9c1i7yXfZ.5O4FQE_HFf6pHlhtqUEBTtvUSz2ru5CceWs12QPYv6feZePYzxoJb_PcCm3gqmfW.zeszXF_OT66lKxNCuFgQReeTVxLX762mV0o49RP44ff29bN4T0d67qJbu7VAs3o91Xi0S5Y=)
        container:
          repository: estafette
          env:
            ESTAFETTE_LOG_FORMAT: v3
          cpu:
            request: 158m
            limit: 316m
          memory:
            request: 483Mi
            limit: 976Mi
          metrics:
            port: 9001
          lifecycle:
            prestopsleep: false
        sidecars:
        - type: openresty
          image: estafette/openresty-sidecar:1.15.8.2
          cpu:
            request: 43m
            limit: 85m
          memory:
            request: 34Mi
            limit: 68Mi
        request:
          timeout: 120s
          maxbodysize: 128M
          clientbodybuffersize: 1m
          proxybuffersnumber: 64
        hosts:
        - estafette.secret(IIZF7TwhQlDeDqtY.s9R8iMp30_frYZoLU7dD1pbdvUg3SCELN3JAXBQ5YrwytnVz.sc58gdlwieDhIsEcQbVLyN3KpkBcjX4b30GYjooRz8zQaXWZFrGeEPJz9SHkSsK7YYOq3ms=)
        internalhosts:
        - estafette.secret(P6NY3iwsirEbkO1Z.RETF5WQACjanX8v4AUMWdQyC0IKfltnOj4mX9_yHvKUyOl5dDdLkHJIuIgdR5FAipt0OZQ==.Rl7F7HcHUCGtHJDyHVsefQ7YzYnEltjUj4Pc9_qD568jOVZCR8d5G436StjCQQRcntXGxdo=)
        basepath: /api
        chaosproof: true
        useGoogleCloudCredentials: true
        manifests:
          files:
          - gke/ingress.yaml
          - gke/ingress-github.yaml
          - gke/ingress-bitbucket.yaml
          - gke/ingress-slack.yaml
          - gke/ingress-pubsub.yaml
          - gke/ingress-cloudsource.yaml
          - gke/integrations-certificate-secret.yaml
          - gke/secret-sa-gke.yaml
          - gke/secret-sa-gcr.yaml
          data:
            IntegrationsHostname: estafette.secret(TLft87lv4YqRTpEk.RTcbrb0mtJ-y3FK49JErE9kLnhi-mruC2kZPwVQdE4MJqn4UOVqr5TnuIf6G4ftZdw==.Ry0bpK4h7oi4nBSz84AtB90LgxL_jOaCyUFc3FhWXY8NesulkHtkMSQOIPQ6M5ZSbe_CcUE=)
        volumemounts:
        - name: client-certs
          mountpath: /cockroach-certs
          volume:
            secret:
              secretName: estafette.client.api
              items:
              - key: key
                path: key
                mode: 0600
              - key: cert
                path: cert
        - name: app-secrets
          mountpath: /secrets
          volume:
            secret:
              secretName: estafette-ci-config-secrets
        - name: app-configs
          mountpath: /configs
          volume:
            configMap:
              name: estafette-ci-config-configs
        - name: gcp-service-account-gke
          mountpath: /gcp-service-account-gke
          volume:
            secret:
              secretName: ${ESTAFETTE_GIT_NAME}-gcp-service-account-gke
        - name: gcp-service-account-gcr
          mountpath: /gcp-service-account-gcr
          volume:
            secret:
              secretName: ${ESTAFETTE_GIT_NAME}-gcp-service-account-gcr

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#release-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  tooling-estafette:
    actions:
    - name: deploy-canary
    - name: deploy-stable
    - name: rollback-canary
    clone: true
    stages:
      deploy:
        image: extensions/gke:dev
        namespace: estafette-ci
        visibility: iap
        iapOauthClientID: estafette.secret(8Nlk-Aq1sDFySTEg.EH4VgB8zQ_Uhimb_MdSPrVyJiOtqAop23D8zDjnksHbVJQ2Q_maGamkn6Kh0TAnD6a_oUpLNTUOUIuxFYmGy_74FqdOCvvvsB5_crRW4dFVWtLq7GRxy-cXzlJ5KjnUaKzXzCPlr17fqhJnBYVCLWQ==.OUMokSQrOO8DjQDtDOSJ_nWqk70cMMF42Q4-SBfJ33jfZiaK9obT5tkyEZmyyfFtVfSRrHo=)
        iapOauthClientSecret: estafette.secret(DtIinOnwxATamw47.3YE8gEmg5Bhrjpbm_oYIrSgY8HVUG97ecLjijXxiLhK7eVOkTe_hlJrEgxcgEplB.97AKjl7ynDZlpMnQ38BY_QIkxiEoO9WbdIjrilJSUQMz96JkMouDmp8CKXvS1TGvTrHJB10=)
        container:
          repository: estafette
          env:
            ESTAFETTE_LOG_FORMAT: v3
          cpu:
            request: 158m
            limit: 316m
          memory:
            request: 483Mi
            limit: 976Mi
          metrics:
            port: 9001
          lifecycle:
            prestopsleep: false
        sidecars:
        - type: openresty
          image: estafette/openresty-sidecar:1.15.8.2
          cpu:
            request: 43m
            limit: 85m
          memory:
            request: 34Mi
            limit: 68Mi
        request:
          timeout: 120s
          maxbodysize: 128M
          clientbodybuffersize: 1m
          proxybuffersnumber: 64
        hosts:
        - estafette.secret(IIZF7TwhQlDeDqtY.s9R8iMp30_frYZoLU7dD1pbdvUg3SCELN3JAXBQ5YrwytnVz.sc58gdlwieDhIsEcQbVLyN3KpkBcjX4b30GYjooRz8zQaXWZFrGeEPJz9SHkSsK7YYOq3ms=)
        - estafette.secret(Ht4w97zYNegDUn90.dQLWAThFkF4B0GoNQVhFXjx8JvWE53Xicu6t00LcQTu83Kt8OBsR.dxjWCCtCykkLkCYBHFhWWS9hKr7I7WtdamC2R0kOioMqTdAQIZ5gtRV0YovWm3wjjqrcP3Y=)
        internalhosts:
        - estafette.secret(P6NY3iwsirEbkO1Z.RETF5WQACjanX8v4AUMWdQyC0IKfltnOj4mX9_yHvKUyOl5dDdLkHJIuIgdR5FAipt0OZQ==.Rl7F7HcHUCGtHJDyHVsefQ7YzYnEltjUj4Pc9_qD568jOVZCR8d5G436StjCQQRcntXGxdo=)
        - estafette.secret(Ms16kDpJJsAW2ttz.5PDwuKRZ8U6NztE7E7iBA3d46dHZoekuYWUXHvtqVsvhjIgmkSZ8tUoWxQJHAD8gv4je5E07dg==.5urwsbdeq1mHjp03TriPCn5l89PYrfQuZXEcC-MhD9rp14Au1heNbzww3acBPVN5rAF9dE0=)
        basepath: /api
        chaosproof: true
        useGoogleCloudCredentials: true
        manifests:
          files:
          - gke/ingress.yaml
          - gke/ingress-github.yaml
          - gke/ingress-bitbucket.yaml
          - gke/ingress-slack.yaml
          - gke/ingress-pubsub.yaml
          - gke/ingress-cloudsource.yaml
          - gke/integrations-certificate-secret.yaml
          data:
            IntegrationsHostname: estafette.secret(TLft87lv4YqRTpEk.RTcbrb0mtJ-y3FK49JErE9kLnhi-mruC2kZPwVQdE4MJqn4UOVqr5TnuIf6G4ftZdw==.Ry0bpK4h7oi4nBSz84AtB90LgxL_jOaCyUFc3FhWXY8NesulkHtkMSQOIPQ6M5ZSbe_CcUE=)
            IntegrationsHostname2: estafette.secret(TPjFkETu4Dig2jmS.IW-QvFT96oSyqX5XZHzO2cOtwao1SxwY8WDgHBDuN6iWnXyyYez1I3mmdWiaKHxVdM_6Lw==.I3WQtUf6sJO46TJbOmHBy8O-x65uRwAC4yjxGgX9c7PR03KvYjQidC4lj_f4brZV509_Uo8=)
        volumemounts:
        # - name: client-certs
        #   mountpath: /cockroach-certs
        #   volume:
        #     secret:
        #       secretName: estafette.client.api
        #       items:
        #       - key: key
        #         path: key
        #         mode: 0600
        #       - key: cert
        #         path: cert
        - name: app-secrets
          mountpath: /secrets
          volume:
            secret:
              secretName: estafette-ci-config-secrets
        - name: app-configs
          mountpath: /configs
          volume:
            configMap:
              name: estafette-ci-config-configs

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#release-status'
        when:
          status == 'succeeded' ||
          status == 'failed'