builder:
  track: dev
  medium: memory

labels:
  type: service
  app-group: estafette-ci
  team: estafette
  language: golang

version:
  semver:
    major: 1
    minor: 0
    patch: 0
    labelTemplate: '{{branch}}-{{auto}}'
    releaseBranch: 1.0.0

triggers:
- pipeline:
    name: github.com/estafette/estafette-ci-db-migrator
    branch: main
  builds:
    branch: main

stages:
  build-lint-and-package:
    parallelStages:
      build:
        image: golang:1.16-alpine
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOGC: off
        commands:
        - go test -short ./...
        - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

      lint-helm-chart:
        image: extensions/helm:dev
        action: lint

      package-helm-chart:
        image: extensions/helm:dev
        action: package

  integration-tests-prepare:
    services:
    - name: cockroachdb
      multiStage: true
      image: cockroachdb/cockroach:v20.2.6
      shell: /bin/bash
      env:
        COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING: "true"
      readiness:
        path: /health?ready=1
        port: 8080
        timeoutSeconds: 120
      commands:
      - /cockroach/cockroach start-single-node --insecure --advertise-addr cockroachdb

    image: estafette/estafette-ci-db-migrator:0.1
    env:
      COCKROACH_CONNECTION_STRING: postgresql://root@cockroachdb:26257/defaultdb?sslmode=disable
      ESTAFETTE_LOG_FORMAT: console

  integration-tests:
    image: golang:1.16-alpine
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOGC: off
    commands:
    - go test -run TestIntegration ./...

  bake:
    image: extensions/docker:dev
    action: build
    inline: |
      FROM scratch

      LABEL maintainer="estafette.io" \
            description="The ${ESTAFETTE_GIT_NAME} is the component that handles api requests and starts build jobs using the estafette-ci-builder"

      COPY ca-certificates.crt /etc/ssl/certs/
      COPY ${ESTAFETTE_GIT_NAME} /

      ENV GRACEFUL_SHUTDOWN_DELAY_SECONDS="20"

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - estafette
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  test-helm-chart:
    services:
    - name: kubernetes
      image: bsycorp/kind:latest-1.19
      readiness:
        path: /kubernetes-ready
        port: 10080
        timeoutSeconds: 120
    image: extensions/helm:dev
    action: test
    values: |-
      secret:
        secretDecryptionKey: 1PsvXVOMkhfAQuBIcIGCtzIdPXNV0NYG

        # tls certificate generated with
        # > openssl req -x509 -sha256 -nodes -days 1024 -newkey rsa:2048 -keyout certificate.key -out certificate.crt
        # > cat certificate.crt certificate.key | base64
        certificatePemFile: |
          -----BEGIN CERTIFICATE-----
          MIIDDDCCAfQCCQDPOxdKcxP9xjANBgkqhkiG9w0BAQsFADBIMQswCQYDVQQGEwJJ
          TzESMBAGA1UECgwJRXN0YWZldHRlMQswCQYDVQQLDAJDSTEYMBYGA1UEAwwPY2ku
          ZXN0YWZldHRlLmlvMB4XDTE5MTExMjE2MTUzOFoXDTIyMDkwMTE2MTUzOFowSDEL
          MAkGA1UEBhMCSU8xEjAQBgNVBAoMCUVzdGFmZXR0ZTELMAkGA1UECwwCQ0kxGDAW
          BgNVBAMMD2NpLmVzdGFmZXR0ZS5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
          AQoCggEBAKw2FPLy7bRfQhh0pA+0VC3Hjeg0zkf1haxd3F3vrPzT8/HyUEHW7OBW
          iU/bgoGey3vWtO0fCcUmQ1/zvgIB/milFth2WrNe87QLPEPyyLgaQVVcaLMPkO9Y
          f6NH+9Dom9hoTXElBOQV20kykPW+6vQJ5LJDM08gJIjrdRIspPts4LR/WR1dlC7Y
          Tb8jNEpnTz8YKSBXpbsgJ4wP8QXKmrKEIVh1R70L3DpvkhzWtxUpd7TjumBEO7J0
          rK7UHE+i01f3ZQoB+dP6aa2Eglh5hW1esjHOv+9r43MtGcUbIUTRXFTXAxW7eyQo
          UXmyOO+8893pIVDd4PjgGe6gLoq2PikCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
          kZVfx38FDkPLF4/Vc0ouX2E3UL/FOsyQ6C/rwI17hB+vMF0fpi9q2rk1pOsMuLyo
          ohU1QgtyL4G0WVLHwofhM/kNZ7fVGZoFb3ElVX80n+3Y0QfQ19CjX0Z51LZN667H
          RQbBhL8VrSply9n7LfgjY/6JgegKHdBz05ip0TD6abhy1luE3QR6n/NnEVxgCuzu
          jfvsJax9IFJskmV+5po9C9M6yx2yUgMev8xs8W0le6K8bFXn9pI7dMKjAU6VSAaB
          Ecj/5bwM8q484hEx3/RdJA7U/iksvGpcSGeIZZKIuPoEGIymP7zknpM1EYnJW4Ms
          capUuV75/Asf/eW6C3lS7A==
          -----END CERTIFICATE-----
          -----BEGIN PRIVATE KEY-----
          MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsNhTy8u20X0IY
          dKQPtFQtx43oNM5H9YWsXdxd76z80/Px8lBB1uzgVolP24KBnst71rTtHwnFJkNf
          874CAf5opRbYdlqzXvO0CzxD8si4GkFVXGizD5DvWH+jR/vQ6JvYaE1xJQTkFdtJ
          MpD1vur0CeSyQzNPICSI63USLKT7bOC0f1kdXZQu2E2/IzRKZ08/GCkgV6W7ICeM
          D/EFypqyhCFYdUe9C9w6b5Ic1rcVKXe047pgRDuydKyu1BxPotNX92UKAfnT+mmt
          hIJYeYVtXrIxzr/va+NzLRnFGyFE0VxU1wMVu3skKFF5sjjvvPPd6SFQ3eD44Bnu
          oC6Ktj4pAgMBAAECggEAbI4q5nr8HJdvsrrUMJIb/j+s1JN09Sdv/BeusghDo5x4
          SivVK6uv5jqmlBBrVAolewr9QfwuzHgyQGoFfH6FQLHQlOMGictxFC2A79Q7ctIa
          HRUDatyFIFtJGkRmGGqI0wHsz0Xmr2CXuqyFdGPE99DEuRpjXZ2FakoColJCLbqL
          qg9kO8zTa8QP6kBvpZr1BMA/jHhaW+BxrVZjvTVSb6P9PGnczKZq1dODScGzJZuj
          4pF5amgSAKBOIP0O5LAoZCqGrDP6/hvH9+UMVgTJdqPRVSjigru3fZ6wC9M0MT4L
          rIBKfrLuhuVi4gUir/5aG542pHXColhN36SQmOMTgQKBgQDVrCqLBrRyNNUC0FsL
          5QetgPdV1W4b8m6kPn6iGVAeKm1jdhoi9bEHEX44/n4J2S6CH9ZPxlSNQN5S/n21
          CfpyzsVBCYDXF5232Gzd3tLB/10LyzbpcsLx8z/yDLX1T7+rK1vjAWF5gyxNZMzF
          hS58KKy8m31bcMS9LkDm9HKd3wKBgQDOU1FYbgDiK9aBLVeQQ/6ACMEFlLp/8S2P
          6JXDZnkzIaESjdaGmO8DMBd2rnoCdMyykb9QDiDhjNa0gBUQzeST94eJ+8dJsB/6
          fCzVfB+HX9ha5L7BZUWiBjvLP8+oEB9kwLTinTETUL/fJxb+4remiwvlYs8gcx5v
          Pi0CmIWU9wKBgAI4ZMTHEA7zv5bk5V1NRvQll+xbaGZ/8Whhgd1bV/rIRBS5gHIG
          jY1eQCqFcnfVuub9P7PagrxpBSZloJbGAMU6otAXMjCJ/UiQxijUDOqZJbVeqjZo
          y9/JwEtamHVxG7PCopTMSeACXe578qjGxoHhxlG7Z+UQWesBVQlRVvOPAoGAM+ur
          kME936yAckliu58gsD+Ds0/WDtQ2TvyMk3t6DG/uBKlEzuI1Y2v6u5b0hSG3UUh0
          CEVF6Px0G0AQDQaC+ulTZlnBsL1tjq8o6SAvHvXzkAv4JNrDRx6idWc9bmGARO5p
          lo1QCDhN0G4Zz1JmPLbI65SN4vCVPBE9amXPV8kCgYBiD0jOTLwaSQLtlqit9WRJ
          L+ZByYDbN4XOU4Jpx1Cy7GQ+OjNFukdeFWz3ANJ7/mz19g2ex60vr8Vy5iw8YB6V
          zT9LCD3MoGlnP21F9KoOg09Qx3DarI7yKv8I29Po6OC4w2Xk5vHDy1mgE+uhQRdz
          EpuAz9izJ7w7uYT9b8buIg==
          -----END PRIVATE KEY-----
        # > cat certificate.key | base64
        certificateKeyFile: |
          -----BEGIN PRIVATE KEY-----
          MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsNhTy8u20X0IY
          dKQPtFQtx43oNM5H9YWsXdxd76z80/Px8lBB1uzgVolP24KBnst71rTtHwnFJkNf
          874CAf5opRbYdlqzXvO0CzxD8si4GkFVXGizD5DvWH+jR/vQ6JvYaE1xJQTkFdtJ
          MpD1vur0CeSyQzNPICSI63USLKT7bOC0f1kdXZQu2E2/IzRKZ08/GCkgV6W7ICeM
          D/EFypqyhCFYdUe9C9w6b5Ic1rcVKXe047pgRDuydKyu1BxPotNX92UKAfnT+mmt
          hIJYeYVtXrIxzr/va+NzLRnFGyFE0VxU1wMVu3skKFF5sjjvvPPd6SFQ3eD44Bnu
          oC6Ktj4pAgMBAAECggEAbI4q5nr8HJdvsrrUMJIb/j+s1JN09Sdv/BeusghDo5x4
          SivVK6uv5jqmlBBrVAolewr9QfwuzHgyQGoFfH6FQLHQlOMGictxFC2A79Q7ctIa
          HRUDatyFIFtJGkRmGGqI0wHsz0Xmr2CXuqyFdGPE99DEuRpjXZ2FakoColJCLbqL
          qg9kO8zTa8QP6kBvpZr1BMA/jHhaW+BxrVZjvTVSb6P9PGnczKZq1dODScGzJZuj
          4pF5amgSAKBOIP0O5LAoZCqGrDP6/hvH9+UMVgTJdqPRVSjigru3fZ6wC9M0MT4L
          rIBKfrLuhuVi4gUir/5aG542pHXColhN36SQmOMTgQKBgQDVrCqLBrRyNNUC0FsL
          5QetgPdV1W4b8m6kPn6iGVAeKm1jdhoi9bEHEX44/n4J2S6CH9ZPxlSNQN5S/n21
          CfpyzsVBCYDXF5232Gzd3tLB/10LyzbpcsLx8z/yDLX1T7+rK1vjAWF5gyxNZMzF
          hS58KKy8m31bcMS9LkDm9HKd3wKBgQDOU1FYbgDiK9aBLVeQQ/6ACMEFlLp/8S2P
          6JXDZnkzIaESjdaGmO8DMBd2rnoCdMyykb9QDiDhjNa0gBUQzeST94eJ+8dJsB/6
          fCzVfB+HX9ha5L7BZUWiBjvLP8+oEB9kwLTinTETUL/fJxb+4remiwvlYs8gcx5v
          Pi0CmIWU9wKBgAI4ZMTHEA7zv5bk5V1NRvQll+xbaGZ/8Whhgd1bV/rIRBS5gHIG
          jY1eQCqFcnfVuub9P7PagrxpBSZloJbGAMU6otAXMjCJ/UiQxijUDOqZJbVeqjZo
          y9/JwEtamHVxG7PCopTMSeACXe578qjGxoHhxlG7Z+UQWesBVQlRVvOPAoGAM+ur
          kME936yAckliu58gsD+Ds0/WDtQ2TvyMk3t6DG/uBKlEzuI1Y2v6u5b0hSG3UUh0
          CEVF6Px0G0AQDQaC+ulTZlnBsL1tjq8o6SAvHvXzkAv4JNrDRx6idWc9bmGARO5p
          lo1QCDhN0G4Zz1JmPLbI65SN4vCVPBE9amXPV8kCgYBiD0jOTLwaSQLtlqit9WRJ
          L+ZByYDbN4XOU4Jpx1Cy7GQ+OjNFukdeFWz3ANJ7/mz19g2ex60vr8Vy5iw8YB6V
          zT9LCD3MoGlnP21F9KoOg09Qx3DarI7yKv8I29Po6OC4w2Xk5vHDy1mgE+uhQRdz
          EpuAz9izJ7w7uYT9b8buIg==
          -----END PRIVATE KEY-----

  clone-charts-repo:
    image: extensions/git-clone:dev
    repo: helm-charts
    branch: main

  publish-helm-chart:
    image: extensions/helm:dev
    action: publish
    repoBranch: main

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  tooling-estafette:
    actions:
    - name: deploy-canary
    - name: deploy-stable
    - name: rollback-canary
      hideBadge: true
    - name: restart-stable
      hideBadge: true
    clone: true
    stages:
      deploy:
        image: extensions/gke:dev
        namespace: estafette-ci
        visibility: iap
        iapOauthClientID: estafette.secret(8Nlk-Aq1sDFySTEg.EH4VgB8zQ_Uhimb_MdSPrVyJiOtqAop23D8zDjnksHbVJQ2Q_maGamkn6Kh0TAnD6a_oUpLNTUOUIuxFYmGy_74FqdOCvvvsB5_crRW4dFVWtLq7GRxy-cXzlJ5KjnUaKzXzCPlr17fqhJnBYVCLWQ==.OUMokSQrOO8DjQDtDOSJ_nWqk70cMMF42Q4-SBfJ33jfZiaK9obT5tkyEZmyyfFtVfSRrHo=)
        iapOauthClientSecret: estafette.secret(DtIinOnwxATamw47.3YE8gEmg5Bhrjpbm_oYIrSgY8HVUG97ecLjijXxiLhK7eVOkTe_hlJrEgxcgEplB.97AKjl7ynDZlpMnQ38BY_QIkxiEoO9WbdIjrilJSUQMz96JkMouDmp8CKXvS1TGvTrHJB10=)
        imagePullSecretUser: estafette.secret(VfjAylmn9HR7zgsc.Gn9lIjF7Pb3Izj6g3fA6wHu-0HNuqxbY7NvwYVCJ5w==.CWRwPC1hcLfF1nipyuEpc7bphtB3-FjwjBGDtYoZBEkoe57G3k5U08tm02qmfujWDUGK-i8=)
        imagePullSecretPassword: estafette.secret(bFuTk7W2-5ZNwN4Y.weEL4hZfGSe7C-wGEAq2EHpoDKnomlKhDLSgc9Y4MtspjPkT0qeeCpmES3cblc5D.7LxMwDlsdDaEJPFbBA7jESxxHr-dj0K7J4GwTfs8JvDjFr-zo3uRFSrIBlKLDuaZJoHNkJQ=)
        container:
          repository: estafette
          env:
            ESTAFETTE_LOG_FORMAT: v3
          cpu:
            request: 158m
          memory:
            request: 483Mi
            limit: 976Mi
          metrics:
            port: 9001
          lifecycle:
            prestopsleep: false
        sidecars:
        - type: openresty
          cpu:
            request: 43m
          memory:
            request: 34Mi
            limit: 68Mi
        customsidecars:
        - name: estafette-ci-api-git-sync
          image: k8s.gcr.io/git-sync:v3.1.5
          env:
          - name: GIT_SYNC_REPO
            value: "estafette.secret(MgMwP-nRoNjystOU.q4Hq0g2nSgFwgjjaBEBEpWYgKJVwkoExjYWBFv4MHTueBDsQchF4MZ2v2YejvF2DGdA3gTGbcwCVrjZJsdDdcA==.q4Hq-hqsEABqjHzaAxpKsWRuJJkploAxw4aXFusPVSyDTHcDcn9zZ1FC-KOnuWUuBAD9nx8=)"
          - name: GIT_SYNC_BRANCH
            value: "git-sync"
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_ROOT
            value: "/configs"
          - name: GIT_SYNC_DEST
            value: "git"
          - name: GIT_SYNC_SSH
            value: "true"
          - name: GIT_SSH_KEY_FILE
            value: "/secrets/git-sync-rsa"
          - name: GIT_KNOWN_HOSTS
            value: "false"
          - name: GIT_SYNC_MAX_SYNC_FAILURES
            value: "10"
          - name: GIT_SYNC_WAIT
            value: "60"
          securityContext:
            runAsUser: 65534 # git-sync user
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 200Mi
          volumeMounts:
          - name: app-configs
            mountPath: /configs
          - name: app-secrets
            mountPath: /secrets
        request:
          timeout: 120s
          maxbodysize: 128M
          clientbodybuffersize: 1m
          proxybuffersnumber: 64
        hosts:
        - estafette.secret(IIZF7TwhQlDeDqtY.s9R8iMp30_frYZoLU7dD1pbdvUg3SCELN3JAXBQ5YrwytnVz.sc58gdlwieDhIsEcQbVLyN3KpkBcjX4b30GYjooRz8zQaXWZFrGeEPJz9SHkSsK7YYOq3ms=)
        - estafette.secret(Ht4w97zYNegDUn90.dQLWAThFkF4B0GoNQVhFXjx8JvWE53Xicu6t00LcQTu83Kt8OBsR.dxjWCCtCykkLkCYBHFhWWS9hKr7I7WtdamC2R0kOioMqTdAQIZ5gtRV0YovWm3wjjqrcP3Y=)
        internalhosts:
        - estafette.secret(P6NY3iwsirEbkO1Z.RETF5WQACjanX8v4AUMWdQyC0IKfltnOj4mX9_yHvKUyOl5dDdLkHJIuIgdR5FAipt0OZQ==.Rl7F7HcHUCGtHJDyHVsefQ7YzYnEltjUj4Pc9_qD568jOVZCR8d5G436StjCQQRcntXGxdo=)
        - estafette.secret(Ms16kDpJJsAW2ttz.5PDwuKRZ8U6NztE7E7iBA3d46dHZoekuYWUXHvtqVsvhjIgmkSZ8tUoWxQJHAD8gv4je5E07dg==.5urwsbdeq1mHjp03TriPCn5l89PYrfQuZXEcC-MhD9rp14Au1heNbzww3acBPVN5rAF9dE0=)
        basepath: /api
        chaosproof: true
        useGoogleCloudCredentials: true
        disableServiceAccountKeyRotation: false
        manifests:
          files:
          - gke/ingress.yaml
          - gke/ingress-github.yaml
          - gke/ingress-bitbucket.yaml
          - gke/ingress-slack.yaml
          - gke/ingress-pubsub.yaml
          - gke/ingress-cloudsource.yaml
          - gke/integrations-certificate-secret.yaml
          data:
            IntegrationsHostname: estafette.secret(TLft87lv4YqRTpEk.RTcbrb0mtJ-y3FK49JErE9kLnhi-mruC2kZPwVQdE4MJqn4UOVqr5TnuIf6G4ftZdw==.Ry0bpK4h7oi4nBSz84AtB90LgxL_jOaCyUFc3FhWXY8NesulkHtkMSQOIPQ6M5ZSbe_CcUE=)
            IntegrationsHostname2: estafette.secret(TPjFkETu4Dig2jmS.IW-QvFT96oSyqX5XZHzO2cOtwao1SxwY8WDgHBDuN6iWnXyyYez1I3mmdWiaKHxVdM_6Lw==.I3WQtUf6sJO46TJbOmHBy8O-x65uRwAC4yjxGgX9c7PR03KvYjQidC4lj_f4brZV509_Uo8=)
        volumemounts:
        - name: client-certs
          mountpath: /cockroach-certs
          volume:
            secret:
              secretName: estafette-ci.client.api
              defaultMode: 0400
        - name: app-secrets
          mountpath: /secrets
          volume:
            secret:
              secretName: estafette-ci-config-secrets
        - name: app-configs
          mountpath: /configs
          volume:
            emptyDir: {}
        - name: app-templates
          mountpath: /templates
          volume:
            configMap:
              name: estafette-ci-manifest-templates-configs

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#release-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  release-helm-chart:
    stages:
      clone-charts-repo:
        image: extensions/git-clone:dev
        repo: helm-charts
        branch: main

      purge-prerelease-helm-charts:
        image: extensions/helm:dev
        action: purge
        repoBranch: main

      create-github-release:
        image: extensions/github-release:dev

  helm-diff:
    stages:
      diff:
        image: extensions/helm:dev
        credentials: gke-tooling-estafette
        action: diff
        tillerless: true
        namespace: estafette
        values: |-
          jobs:
            namespace: estafette-ci-jobs
          secret:
            valuesAreBase64Encoded: true
            decryptionKey: MVBzdlhWT01raGZBUXVCSWNJR0N0eklkUFhOVjBOWUcK
            useLetsEncryptCertificateAnnotation: true
          hostnames:
          - estafette.secret(z6C9Piz4EhMxWMc8.uxcITmg39HiLJuuqSyPRM06PTWNd6S1x1QxfYYeyGoBLcgkM)
          jaeger:
            enable: true
