apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Name}}-bitbucket
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
  annotations:
    kubernetes.io/ingress.class: "nginx-public"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    # the list of bitbucket's ip addresses is too large and too dynamic, so allowing all traffic for now (https://bitbucket.org/blog/update-to-outgoing-webhook-ip-addresses)
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "{{.NginxIngressClientBodyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{.NginxIngressProxyBodySize}}"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "{{.NginxIngressProxyBuffersNumber}}"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "{{.NginxIngressProxyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{.NginxIngressProxyConnectTimeout}}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{.NginxIngressProxySendTimeout}}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{.NginxIngressProxyReadTimeout}}"
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "true"
    estafette.io/cloudflare-hostnames: "{{.ManifestData.IntegrationsHostname}},{{.ManifestData.IntegrationsHostname2}}"
spec:
  tls:
  - hosts:
    - {{.ManifestData.IntegrationsHostname}}
    - {{.ManifestData.IntegrationsHostname2}}
    secretName: {{.Name}}-integrations-letsencrypt-certificate
  rules:
  - host: {{.ManifestData.IntegrationsHostname}}
    http:
      paths:
      - path: /api/integrations/bitbucket
        backend:
          serviceName: {{.Name}}
          servicePort: https
  - host: {{.ManifestData.IntegrationsHostname2}}
    http:
      paths:
      - path: /api/integrations/bitbucket
        backend:
          serviceName: {{.Name}}
          servicePort: https