integrations:
  github:
    enable: true
    installationOrganizations:
    - installation: 15
      organizations:
      - name: Estafette
    - installation: 83
      organizations:
      - name: Estafette

  bitbucket:
    enable: true
    key: ci.estafette.io
    name: Estafette CI
    ownerOrganizations:
    - owner: estafette
      organizations:
      - name: Estafette

  slack:
    enable: true
    clientID: d9ew90weoijewjke
    clientSecret: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    appVerificationToken: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    appOAuthAccessToken: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)

  pubsub:
    enable: true
    defaultProject: estafette
    endpoint: https://ci-integrations.estafette.io/api/integrations/pubsub/events
    audience: estafette-audience
    serviceAccountEmail: estafette@estafette.iam.gserviceaccount.com
    subscriptionNameSuffix: ~estafette-ci-pubsub-trigger
    subscriptionIdleExpirationDays: 365

  cloudsource:
    enable: true
    projectOrganizations:
    - project: estafette
      organizations:
      - name: Estafette

  prometheus:
    enable: true
    serverURL: http://prometheus-server.monitoring.svc.cluster.local
    scrapeIntervalSeconds: 10

  bigquery:
    enable: true
    projectID: my-gcp-project
    dataset: my-dataset

  gcs:
    enable: true
    projectID: my-gcp-project
    bucket: my-bucket
    logsDir: logs

  cloudsource:
    enable: true
    projectOrganizations:
    - project: estafette
      organizations:
      - name: Estafette

apiServer:
  baseURL: https://ci.estafette.io/
  integrationsURL: https://ci-integrations.estafette.io/
  serviceURL: http://estafette-ci-api.estafette.svc.cluster.local/
  logWriters:
  - database
  - cloudstorage
  logReader: database
  injectStagesPerOperatingSystem:
    linux:
      build:
        before:
        - name: envvars
          image: extensions/envvars:stable
        after:
        - name: snyk
          image: extensions/snyk:stable-golang
          labelSelector:
            language: golang
      release:
        before: []
        after:
        - name: envvars
          image: extensions/envvars:dev
      bot:
        before: []
        after:
        - name: envvars
          image: extensions/envvars:dev
    windows:
      build:
        before:
        - name: envvars
          image: extensions/envvars:windowsservercore-ltsc2019
        after: []
      release:
        before: []
        after:
        - name: envvars
          image: extensions/envvars:windowsservercore-ltsc2019
      bot:
        before: []
        after:
        - name: envvars
          image: extensions/envvars:windowsservercore-ltsc2019
  injectCommandsPerOperatingSystemAndShell:
    linux:
      /bin/sh:
        before: []
        after: []
      /bin/bash:
        before: []
        after: []
    windows:
      cmd:
        before:
        - netsh interface ipv4 set subinterface 31 mtu=1410
        after: []
      powershell:
        before:
        - Get-NetAdapter | Where-Object Name -like "*Ethernet*" | ForEach-Object { & netsh interface ipv4 set subinterface $_.InterfaceIndex mtu=1410 store=persistent }
        after: []
  dockerConfigPerOperatingSystem:
    linux:
      runType: dind
      mtu: 1460
      bip: 192.168.1.1/24
      networks:
      - name: estafette
        subnet: 192.168.2.1/24
        gateway: 192.168.2.1
      registryMirror: https://mirror.gcr.io
    windows:
      runType: dod
      mtu: 1410

auth:
  jwt:
    domain: ci.estafette.io
    key: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
  administrators:
  - admin1@server.com
  - admin2@server.com
  organizations:
  - name: Org A
    oauthProviders:
    - name: google
      clientID: abcdasa
      clientSecret: asdsddsfdfs
      allowedIdentitiesRegex: .+@estafette\.io
  - name: Org B
    oauthProviders:
    - name: microsoft
      clientID: abcdasa
      clientSecret: asdsddsfdfs
      allowedIdentitiesRegex: .+@estafette\.io
  - name: Org C
    oauthProviders:
    - name: github
    clientID: abcdasa
    clientSecret: asdsddsfdfs
    allowedIdentitiesRegex: .+@estafette\.io

jobs:
  namespace: estafette-ci-jobs
  serviceAccount: estafette-ci-builder

  defaultCPUCores: 2.0
  minCPUCores: 0.2
  maxCPUCores: 60.0
  cpuRequestRatio: 1.0
  cpuLimitRatio: 2.0

  defaultMemoryBytes: 8589934592
  minMemoryBytes: 134217728
  maxMemoryBytes: 214748364800
  memoryRequestRatio: 1.25
  memoryLimitRatio: 1.0

  build:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - privileged
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          preference:
            matchExpressions:
            - key: cloud.google.com/gke-preemptible
              operator: In
              values:
              - "true"
    tolerations:
    - key: role
      operator: Equal
      value: privileged
      effect: NoSchedule
    - key: cloud.google.com/gke-preemptible
      operator: Equal
      value: "true"
      effect: NoSchedule

  release:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - privileged
            - key: cloud.google.com/gke-preemptible
              operator: DoesNotExist
    tolerations:
    - key: role
      operator: Equal
      value: privileged
      effect: NoSchedule

  bot:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - privileged
            - key: cloud.google.com/gke-preemptible
              operator: DoesNotExist
    tolerations:
    - key: role
      operator: Equal
      value: privileged
      effect: NoSchedule

database:
  databaseName: estafette_ci_api
  host: cockroachdb-public.estafette.svc.cluster.local
  insecure: true
  certificateDir: /cockroachdb-certificates/cockroachdb.crt
  port: 26257
  user: myuser
  password: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)

queue:
  hosts:
  - estafette-ci-queue-0.estafette-ci-queue
  subjectCron: event.cron
  subjectGit: event.git
  subjectGithub: event.github
  subjectBitbucket: event.bitbucket

manifestPreferences:
  labelRegexes:
    type: api|web|library|container
  builderOperatingSystems:
  - linux
  - windows
  builderTracksPerOperatingSystem:
    linux:
    - stable
    - beta
    - dev
    windows:
    - windowsservercore-1809
    - windowsservercore-1909
    - windowsservercore-ltsc2019

catalog:
  filters:
  - type
  - team

credentials:
- name: container-registry-extensions
  type: container-registry
  repository: extensions
  username: username
  password: secret
- name: container-registry-estafette
  type: container-registry
  repository: estafette
  username: username
  password: secret
- name: gke-estafette-production
  type: kubernetes-engine
  project: estafette-production
  region: europe-west2
  cluster: production-europe-west2
  serviceAccountKeyfile: '{}'
  defaults:
    namespace: estafette
    container:
      repository: estafette
    sidecars:
    - type: openresty
      image: estafette/openresty-sidecar:1.13.6.1-alpine
    autoscale:
      min: 2
- name: gke-estafette-development
  type: kubernetes-engine
  project: estafette-development
  cluster: development-europe-west2
  region: europe-west2
  serviceAccountKeyfile: '{}'
- name: bitbucket-api-token
  type: bitbucket-api-token
  token: sometoken
- name: github-api-token
  type: github-api-token
  token: sometoken
- name: slack-webhook-estafette
  type: slack-webhook
  workspace: estafette
  webhook: somewebhookurl
- name: my-nuget-server
  type: nuget-server
  apiUrl: https://my-nuget-server.com
  apiKey: my-nuget-key
- name: my-sonarqube-server
  type: sonarqube-server
  apiUrl: https://my-sonarqube-server.com

trustedImages:
- path: extensions/docker
  runDocker: true
  injectedCredentialTypes:
  - container-registry
- path: extensions/gke
  injectedCredentialTypes:
  - kubernetes-engine
- path: extensions/bitbucket-status
  injectedCredentialTypes:
  - bitbucket-api-token
- path: extensions/github-status
  injectedCredentialTypes:
  - github-api-token
- path: extensions/slack-build-status
  injectedCredentialTypes:
  - slack-webhook
- path: extensions/dotnet
  injectedCredentialTypes:
  - nuget-server
  - sonarqube-server
- path: docker
  runDocker: true
- path: multiple-git-sources-test
  injectedCredentialTypes:
  - bitbucket-api-token
  - github-api-token
  - cloudsource-api-token