credentials:
- name: container-registry-extensions
  type: container-registry
  repository: extensions
  username: username
  password: secret
- name: container-registry-estafette
  type: container-registry
  repository: estafette
  username: username
  password: secret
- name: gke-estafette-production
  type: kubernetes-engine
  project: estafette-production
  region: europe-west2
  cluster: production-europe-west2
  serviceAccountKeyfile: '{}'
  defaults:
    namespace: estafette
    container:
      repository: estafette
    sidecars:
    - type: openresty
      image: estafette/openresty-sidecar:1.13.6.1-alpine
    autoscale:
      min: 2
- name: gke-estafette-development
  type: kubernetes-engine
  project: estafette-development
  cluster: development-europe-west2
  region: europe-west2
  serviceAccountKeyfile: '{}'
- name: bitbucket-api-token
  type: bitbucket-api-token
  token: sometoken
- name: github-api-token
  type: github-api-token
  token: sometoken
- name: slack-webhook-estafette
  type: slack-webhook
  workspace: estafette
  webhook: somewebhookurl
- name: my-nuget-server
  type: nuget-server
  apiUrl: https://my-nuget-server.com
  apiKey: my-nuget-key
- name: my-sonarqube-server
  type: sonarqube-server
  apiUrl: https://my-sonarqube-server.com