apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-api.labels" . | indent 4 }}
data:
  config.yaml: |-
    {{- with .Values.config }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}