{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  labels:
    {{- include "estafette-ci-api.labels" . | nindent 4 }}
data:
  {{- with .Values.config.files }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
{{- end -}}
