{{- $fullName := include "estafette-ci-api.fullname" . -}}
{{ if $.Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else if $.Capabilities.APIVersions.Has "apps/v1beta2" }}
apiVersion: apps/v1beta2
{{- else if $.Capabilities.APIVersions.Has "apps/v1beta1" }}
apiVersion: apps/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  labels:
    {{- include "estafette-ci-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "estafette-ci-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.config.enabled .Values.secret.enabled .Values.deployment.podAnnotations }}
      annotations:
      {{- if or .Values.config.enabled }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- if or .Values.secret.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
      {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "estafette-ci-api.selectorLabels" . | nindent 8 }}
        {{- range $key, $value := .Values.deployment.extraPodLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      {{- if or .Values.image.credentials .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- if .Values.image.credentials }}
        - name: {{ template "estafette-ci-api.fullname" . }}.registry
      {{- end }}
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "estafette-ci-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "ESTAFETTE_LOG_FORMAT"
              value: "{{ .Values.logFormat }}"
            - name: "ESTAFETTE_LOG_LEVEL"
              value: "{{ .Values.logLevel }}"
          {{- with .Values.deployment.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- if or .Values.config.enabled .Values.secret.enabled .Values.deployment.extraVolumeMounts .Values.extraConfigmaps .Values.extraSecrets }}
          volumeMounts:
          {{- if .Values.config.enabled }}
          - name: configs
            mountPath: /configs
          {{- end }}
          {{- if .Values.secret.enabled }}
          - name: secrets
            mountPath: /secrets
          {{- end }}
          {{- range .Values.extraConfigmaps }}
          {{- if .mountPath }}
          - name: configs-{{ .key }}
            mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
          {{- range .Values.extraSecrets }}
          {{- if .mountPath }}
          - name: secrets-{{ .key }}
            mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
          {{- with .Values.deployment.extraVolumeMounts }}
          {{- tpl . $ | nindent 10 }}
          {{- end }}
          {{- end }}
        {{- with .Values.deployment.extraContainers }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: 300
      {{- if or .Values.config.enabled .Values.secret.enabled .Values.deployment.extraVolumes .Values.extraConfigmaps .Values.extraSecrets }}
      volumes:
      {{- if .Values.config.enabled }}
      - name: configs
        configMap:
          name: {{ include "estafette-ci-api.fullname" . }}
      {{- end }}
      {{- if .Values.secret.enabled }}
      - name: secrets
        secret:
          secretName: {{ include "estafette-ci-api.fullname" . }}
      {{- end }}
      {{- range .Values.extraConfigmaps }}
      {{- if .mountPath }}
      - name: configs-{{ .key }}
        configMap: 
          name: {{ $fullName }}.{{ .key }}
      {{- end }}
      {{- end }}
      {{- range .Values.extraSecrets }}
      {{- if .mountPath }}
      - name: secrets-{{ .key }}
        secret:
          secretName: {{ $fullName }}.{{ .key }}
      {{- end }}
      {{- end }}
      {{- with .Values.deployment.extraVolumes }}
      {{- tpl . $ | nindent 6 }}
      {{- end }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
