apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  labels:
{{ include "estafette-ci-api.labels" . | indent 4 }}
type: Opaque
data:
  secretDecryptionKey: {{.Values.secret.secretDecryptionKey | toString | b64enc}}
  {{- with .Values.secret.githubPrivateKey }}
  private-key.pem: {{ . | toString | b64enc}}
  {{- end }}