{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  labels:
    {{- include "estafette-ci-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $secret := lookup "v1" "Secret" .Release.Namespace (include "estafette-ci-api.fullname" .) | default dict  -}}

  {{- if .Values.secret.secretDecryptionKey }}
  secretDecryptionKey: {{ .Values.secret.secretDecryptionKey | b64enc }}
  {{- else if $secret }}
  {{- if $secret.data.secretDecryptionKey }}
  secretDecryptionKey: {{ $secret.data.secretDecryptionKey }}
  {{- else }}
  secretDecryptionKey: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- else }}
  secretDecryptionKey: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

  {{- if .Values.secret.jwtKey }}
  jwtKey: {{ .Values.secret.jwtKey | b64enc }}
  {{- else if $secret }}
  {{- if $secret.data.jwtKey }}
  jwtKey: {{ $secret.data.secretDjwtKeyecryptionKey }}
  {{- else }}
  jwtKey: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- else }}
  jwtKey: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

{{- end }}