apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-api.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.secret.valuesAreBase64Encoded }}
  {{ if .Values.secret.secretDecryptionKey }}
  secretDecryptionKey: {{.Values.secret.secretDecryptionKey | toString}}
  {{- else }}
  secretDecryptionKey: {{ randAlphaNum 32 | toString}}
  {{- end }}
  {{- with .Values.secret.githubPrivateKey }}
  githubPrivateKey: {{ . | toString}}
  {{- end }}
  {{- else }}
  {{ if .Values.secret.secretDecryptionKey }}
  secretDecryptionKey: {{.Values.secret.secretDecryptionKey | toString | b64enc}}
  {{- else }}
  secretDecryptionKey: {{ randAlphaNum 32 | toString | b64enc}}
  {{- end }}
  {{- with .Values.secret.githubPrivateKey }}
  githubPrivateKey: {{ . | toString | b64enc}}
  {{- end }}
  {{- end }}