apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}-secrets
  labels:
{{ include "estafette-ci-api.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.secret.valuesAreBase64Encoded }}
  secretDecryptionKey: {{.Values.secret.secretDecryptionKey | toString}}
  {{- with .Values.secret.githubPrivateKey }}
  private-key.pem: {{ . | toString}}
  {{- end }}
  {{- else }}
  secretDecryptionKey: {{.Values.secret.secretDecryptionKey | toString | b64enc}}
  {{- with .Values.secret.githubPrivateKey }}
  private-key.pem: {{ . | toString | b64enc}}
  {{- end }}
  {{- end }}