{{- if .Values.openresty.enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}.tls
  labels:
{{ include "estafette-ci-api.labels" . | indent 4 }}
  {{- if .Values.secret.useLetsEncryptCertificateAnnotation }}
  annotations:
    estafette.io/letsencrypt-certificate: 'true'
    estafette.io/letsencrypt-certificate-hostnames: '{{ .Values.secret.letsEncryptHostnames | join "," }}'
  {{- end }}
type: Opaque
{{- if not .Values.secret.useLetsEncryptCertificateAnnotation }}
data:
  ssl.pem: {{.Values.secret.certificatePemFile | toString | b64enc}}
  ssl.key: {{.Values.secret.certificateKeyFile | toString | b64enc}}
{{- end }}
{{- end -}}