{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  labels:
    {{- include "estafette-ci-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.files }}
    {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
{{- end }}