{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  labels:
    {{- include "estafette-ci-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  {{- if .Values.secret.secretDecryptionKey }}
  secretDecryptionKey: {{ .Values.secret.secretDecryptionKey | b64enc | quote }}
  {{- else }}
  secretDecryptionKey: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.jwtKey }}
  jwtKey: {{ .Values.secret.jwtKey | b64enc | quote }}
  {{- else }}
  jwtKey: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}