apiVersion: v1
kind: Service
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-api.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.openresty.enable }}
      targetPort: https
      {{- else }}
      targetPort: web
      {{- end }}
      protocol: TCP
      name: https
  selector:
{{ include "estafette-ci-api.selectorLabels" . | indent 4 }}
