// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package bitbucketapi is a generated GoMock package.
package bitbucketapi

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddInstallation mocks base method.
func (m *MockClient) AddInstallation(ctx context.Context, installation BitbucketAppInstallation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInstallation", ctx, installation)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddInstallation indicates an expected call of AddInstallation.
func (mr *MockClientMockRecorder) AddInstallation(ctx, installation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInstallation", reflect.TypeOf((*MockClient)(nil).AddInstallation), ctx, installation)
}

// GenerateJWT mocks base method.
func (m *MockClient) GenerateJWT() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJWT")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJWT indicates an expected call of GenerateJWT.
func (mr *MockClientMockRecorder) GenerateJWT() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJWT", reflect.TypeOf((*MockClient)(nil).GenerateJWT))
}

// GetAccessToken mocks base method.
func (m *MockClient) GetAccessToken(ctx context.Context) (AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken", ctx)
	ret0, _ := ret[0].(AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockClientMockRecorder) GetAccessToken(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockClient)(nil).GetAccessToken), ctx)
}

// GetEstafetteManifest mocks base method.
func (m *MockClient) GetEstafetteManifest(ctx context.Context, accesstoken AccessToken, event RepositoryPushEvent) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEstafetteManifest", ctx, accesstoken, event)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEstafetteManifest indicates an expected call of GetEstafetteManifest.
func (mr *MockClientMockRecorder) GetEstafetteManifest(ctx, accesstoken, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEstafetteManifest", reflect.TypeOf((*MockClient)(nil).GetEstafetteManifest), ctx, accesstoken, event)
}

// GetInstallations mocks base method.
func (m *MockClient) GetInstallations(ctx context.Context) ([]*BitbucketAppInstallation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstallations", ctx)
	ret0, _ := ret[0].([]*BitbucketAppInstallation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstallations indicates an expected call of GetInstallations.
func (mr *MockClientMockRecorder) GetInstallations(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstallations", reflect.TypeOf((*MockClient)(nil).GetInstallations), ctx)
}

// GetWorkspace mocks base method.
func (m *MockClient) GetWorkspace(ctx context.Context, installation BitbucketAppInstallation) (*Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspace", ctx, installation)
	ret0, _ := ret[0].(*Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspace indicates an expected call of GetWorkspace.
func (mr *MockClientMockRecorder) GetWorkspace(ctx, installation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspace", reflect.TypeOf((*MockClient)(nil).GetWorkspace), ctx, installation)
}

// JobVarsFunc mocks base method.
func (m *MockClient) JobVarsFunc(ctx context.Context) func(context.Context, string, string, string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobVarsFunc", ctx)
	ret0, _ := ret[0].(func(context.Context, string, string, string) (string, error))
	return ret0
}

// JobVarsFunc indicates an expected call of JobVarsFunc.
func (mr *MockClientMockRecorder) JobVarsFunc(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobVarsFunc", reflect.TypeOf((*MockClient)(nil).JobVarsFunc), ctx)
}

// RemoveInstallation mocks base method.
func (m *MockClient) RemoveInstallation(ctx context.Context, installation BitbucketAppInstallation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveInstallation", ctx, installation)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveInstallation indicates an expected call of RemoveInstallation.
func (mr *MockClientMockRecorder) RemoveInstallation(ctx, installation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveInstallation", reflect.TypeOf((*MockClient)(nil).RemoveInstallation), ctx, installation)
}
