integrations:
  github:
    privateKeyPath: /github-app-key/private-key.pem
    appID: 15
    clientID: asdas2342
    clientSecret: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    webhookSecret: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    whitelistedInstallations:
    - 15
    - 83

  bitbucket:
    apiKey: sd9ewiwuejkwejkewk
    appOAuthKey: 2390w3e90jdsk
    appOAuthSecret: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    whitelistedOwners:
    - estafette

  slack:
    clientID: d9ew90weoijewjke
    clientSecret: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    appVerificationToken: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)
    appOAuthAccessToken: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)

  prometheus:
    serverURL: http://prometheus-server.monitoring.svc.cluster.local
    scrapeIntervalSeconds: 10

  bigquery:
    enable: true
    projectID: my-gcp-project
    dataset: my-dataset

  gcs:
    projectID: my-gcp-project
    bucket: my-bucket
    logsDir: logs

  cloudsource:
    whitelistedProjects:
    - estafette

apiServer:
  baseURL: https://ci.estafette.io/
  serviceURL: http://estafette-ci-api.estafette.svc.cluster.local/
  logWriters:
  - database
  - cloudstorage
  logReader: database

auth:
  iap:
    enable: true
    audience: /projects/***/global/backendServices/***
  apiKey: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)

jobs:
  namespace: estafette-ci-jobs
  minCPUCores: 0.1
  maxCPUCores: 3.5
  cpuRequestRatio: 1.0
  minMemoryBytes: 67108864
  maxMemoryBytes: 12884901888
  memoryRequestRatio: 1.25

database:
  databaseName: estafette_ci_api
  host: cockroachdb-public.estafette.svc.cluster.local
  insecure: true
  certificateDir: /cockroachdb-certificates/cockroachdb.crt
  port: 26257
  user: myuser
  password: estafette.secret(deFTz5Bdjg6SUe29.oPIkXbze5G9PNEWS2-ZnArl8BCqHnx4MdTdxHg37th9u)

credentials:
- name: container-registry-extensions
  type: container-registry
  repository: extensions
  username: username
  password: secret
- name: container-registry-estafette
  type: container-registry
  repository: estafette
  username: username
  password: secret
- name: gke-estafette-production
  type: kubernetes-engine
  project: estafette-production
  region: europe-west2
  cluster: production-europe-west2
  serviceAccountKeyfile: '{}'
  defaults:
    namespace: estafette
    container:
      repository: estafette
    sidecars:
    - type: openresty
      image: estafette/openresty-sidecar:1.13.6.1-alpine
    autoscale:
      min: 2
- name: gke-estafette-development
  type: kubernetes-engine
  project: estafette-development
  cluster: development-europe-west2
  region: europe-west2
  serviceAccountKeyfile: '{}'
- name: bitbucket-api-token
  type: bitbucket-api-token
  token: sometoken
- name: github-api-token
  type: github-api-token
  token: sometoken
- name: slack-webhook-estafette
  type: slack-webhook
  workspace: estafette
  webhook: somewebhookurl
- name: my-nuget-server
  type: nuget-server
  apiUrl: https://my-nuget-server.com
  apiKey: my-nuget-key
- name: my-sonarqube-server
  type: sonarqube-server
  apiUrl: https://my-sonarqube-server.com

trustedImages:
- path: extensions/docker
  runDocker: true
  injectedCredentialTypes:
  - container-registry
- path: extensions/gke
  injectedCredentialTypes:
  - kubernetes-engine
- path: extensions/bitbucket-status
  injectedCredentialTypes:
  - bitbucket-api-token
- path: extensions/github-status
  injectedCredentialTypes:
  - github-api-token
- path: extensions/slack-build-status
  injectedCredentialTypes:
  - slack-webhook
- path: extensions/dotnet
  injectedCredentialTypes:
  - nuget-server
  - sonarqube-server
- path: docker
  runDocker: true
- path: multiple-git-sources-test
  injectedCredentialTypes:
  - bitbucket-api-token
  - github-api-token
  - cloudsource-api-token

registryMirror: https://mirror.gcr.io
dindMtu: 1360
dindBip: 192.168.1.1/24
dindNetwork:
  name: estafette
  subnet: 192.168.2.1/24
  gateway: 192.168.2.1