// Generating protobuf code
//
// For golang install protoc (if already not installed)
//    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
// and run the following command from the project root directory
//    protoc --go_out=. --go-grpc_out=. gcs-migrator/protos/migrate.proto
//
// For python code, create virtualenv as below
//    cd gcs-migrator
//    virtualenv -p python3 env
//    pip install grpcio grpcio-tools google-cloud-storage
// Or activate existing env
//    source gcs-migrator/env/bin/activate
// then run the following commands from the project root directory
//    python gcs-migrator/codegen.py

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: gcs-migrator/protos/migrate.proto

package migrationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *LogObject) Reset() {
	*x = LogObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogObject) ProtoMessage() {}

func (x *LogObject) ProtoReflect() protoreflect.Message {
	mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogObject.ProtoReflect.Descriptor instead.
func (*LogObject) Descriptor() ([]byte, []int) {
	return file_gcs_migrator_protos_migrate_proto_rawDescGZIP(), []int{0}
}

func (x *LogObject) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *LogObject) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromLogObject *LogObject `protobuf:"bytes,2,opt,name=from_log_object,json=fromLogObject,proto3" json:"from_log_object,omitempty"`
	ToLogObject   *LogObject `protobuf:"bytes,3,opt,name=to_log_object,json=toLogObject,proto3" json:"to_log_object,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_gcs_migrator_protos_migrate_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetFromLogObject() *LogObject {
	if x != nil {
		return x.FromLogObject
	}
	return nil
}

func (x *Request) GetToLogObject() *LogObject {
	if x != nil {
		return x.ToLogObject
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Migrations []*Migration `protobuf:"bytes,1,rep,name=migrations,proto3" json:"migrations,omitempty"`
	Batches    int64        `protobuf:"varint,2,opt,name=batches,proto3" json:"batches,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_gcs_migrator_protos_migrate_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMigrations() []*Migration {
	if x != nil {
		return x.Migrations
	}
	return nil
}

func (x *Response) GetBatches() int64 {
	if x != nil {
		return x.Batches
	}
	return 0
}

type Migration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromLogObject *LogObject      `protobuf:"bytes,2,opt,name=from_log_object,json=fromLogObject,proto3" json:"from_log_object,omitempty"`
	ToLogObject   *LogObject      `protobuf:"bytes,3,opt,name=to_log_object,json=toLogObject,proto3" json:"to_log_object,omitempty"`
	Error         *MigrationError `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *Migration) Reset() {
	*x = Migration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_gcs_migrator_protos_migrate_proto_rawDescGZIP(), []int{3}
}

func (x *Migration) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Migration) GetFromLogObject() *LogObject {
	if x != nil {
		return x.FromLogObject
	}
	return nil
}

func (x *Migration) GetToLogObject() *LogObject {
	if x != nil {
		return x.ToLogObject
	}
	return nil
}

func (x *Migration) GetError() *MigrationError {
	if x != nil {
		return x.Error
	}
	return nil
}

type MigrationError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Errors  []*MigrationErrorDetail `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *MigrationError) Reset() {
	*x = MigrationError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationError) ProtoMessage() {}

func (x *MigrationError) ProtoReflect() protoreflect.Message {
	mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationError.ProtoReflect.Descriptor instead.
func (*MigrationError) Descriptor() ([]byte, []int) {
	return file_gcs_migrator_protos_migrate_proto_rawDescGZIP(), []int{4}
}

func (x *MigrationError) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MigrationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MigrationError) GetErrors() []*MigrationErrorDetail {
	if x != nil {
		return x.Errors
	}
	return nil
}

type MigrationErrorDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain  string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MigrationErrorDetail) Reset() {
	*x = MigrationErrorDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationErrorDetail) ProtoMessage() {}

func (x *MigrationErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_gcs_migrator_protos_migrate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationErrorDetail.ProtoReflect.Descriptor instead.
func (*MigrationErrorDetail) Descriptor() ([]byte, []int) {
	return file_gcs_migrator_protos_migrate_proto_rawDescGZIP(), []int{5}
}

func (x *MigrationErrorDetail) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MigrationErrorDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MigrationErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gcs_migrator_protos_migrate_proto protoreflect.FileDescriptor

var file_gcs_migrator_protos_migrate_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x63, 0x73, 0x2d, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62,
	0x22, 0x37, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x95, 0x01, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3e, 0x0a, 0x0f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6c, 0x6f,
	0x67, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3a, 0x0a, 0x0d, 0x74, 0x6f, 0x5f, 0x6c, 0x6f, 0x67, 0x5f,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x0b, 0x74, 0x6f, 0x4c, 0x6f, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x22, 0x5c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x0a, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x22,
	0xd9, 0x01, 0x0a, 0x09, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3e, 0x0a,
	0x0f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0d,
	0x66, 0x72, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3a, 0x0a,
	0x0d, 0x74, 0x6f, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0b, 0x74, 0x6f,
	0x4c, 0x6f, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x79, 0x0a, 0x0e, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x60, 0x0a, 0x14, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x45, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x12, 0x14,
	0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42,
	0x24, 0x5a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x65, 0x73, 0x74, 0x61, 0x66, 0x65, 0x74, 0x74, 0x65, 0x2f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gcs_migrator_protos_migrate_proto_rawDescOnce sync.Once
	file_gcs_migrator_protos_migrate_proto_rawDescData = file_gcs_migrator_protos_migrate_proto_rawDesc
)

func file_gcs_migrator_protos_migrate_proto_rawDescGZIP() []byte {
	file_gcs_migrator_protos_migrate_proto_rawDescOnce.Do(func() {
		file_gcs_migrator_protos_migrate_proto_rawDescData = protoimpl.X.CompressGZIP(file_gcs_migrator_protos_migrate_proto_rawDescData)
	})
	return file_gcs_migrator_protos_migrate_proto_rawDescData
}

var file_gcs_migrator_protos_migrate_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gcs_migrator_protos_migrate_proto_goTypes = []interface{}{
	(*LogObject)(nil),            // 0: migrationpb.LogObject
	(*Request)(nil),              // 1: migrationpb.Request
	(*Response)(nil),             // 2: migrationpb.Response
	(*Migration)(nil),            // 3: migrationpb.Migration
	(*MigrationError)(nil),       // 4: migrationpb.MigrationError
	(*MigrationErrorDetail)(nil), // 5: migrationpb.MigrationErrorDetail
}
var file_gcs_migrator_protos_migrate_proto_depIdxs = []int32{
	0, // 0: migrationpb.Request.from_log_object:type_name -> migrationpb.LogObject
	0, // 1: migrationpb.Request.to_log_object:type_name -> migrationpb.LogObject
	3, // 2: migrationpb.Response.migrations:type_name -> migrationpb.Migration
	0, // 3: migrationpb.Migration.from_log_object:type_name -> migrationpb.LogObject
	0, // 4: migrationpb.Migration.to_log_object:type_name -> migrationpb.LogObject
	4, // 5: migrationpb.Migration.error:type_name -> migrationpb.MigrationError
	5, // 6: migrationpb.MigrationError.errors:type_name -> migrationpb.MigrationErrorDetail
	1, // 7: migrationpb.Service.Migrate:input_type -> migrationpb.Request
	2, // 8: migrationpb.Service.Migrate:output_type -> migrationpb.Response
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_gcs_migrator_protos_migrate_proto_init() }
func file_gcs_migrator_protos_migrate_proto_init() {
	if File_gcs_migrator_protos_migrate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gcs_migrator_protos_migrate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcs_migrator_protos_migrate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcs_migrator_protos_migrate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcs_migrator_protos_migrate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Migration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcs_migrator_protos_migrate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcs_migrator_protos_migrate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationErrorDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gcs_migrator_protos_migrate_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gcs_migrator_protos_migrate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gcs_migrator_protos_migrate_proto_goTypes,
		DependencyIndexes: file_gcs_migrator_protos_migrate_proto_depIdxs,
		MessageInfos:      file_gcs_migrator_protos_migrate_proto_msgTypes,
	}.Build()
	File_gcs_migrator_protos_migrate_proto = out.File
	file_gcs_migrator_protos_migrate_proto_rawDesc = nil
	file_gcs_migrator_protos_migrate_proto_goTypes = nil
	file_gcs_migrator_protos_migrate_proto_depIdxs = nil
}
