# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: migrate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmigrate.proto\x12\x0bmigrationpb\")\n\tLogObject\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"u\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x03\x12/\n\x0f\x66rom_log_object\x18\x02 \x01(\x0b\x32\x16.migrationpb.LogObject\x12-\n\rto_log_object\x18\x03 \x01(\x0b\x32\x16.migrationpb.LogObject\"G\n\x08Response\x12*\n\nmigrations\x18\x01 \x03(\x0b\x32\x16.migrationpb.Migration\x12\x0f\n\x07\x62\x61tches\x18\x02 \x01(\x03\"\xb2\x01\n\tMigration\x12\n\n\x02id\x18\x01 \x01(\x03\x12/\n\x0f\x66rom_log_object\x18\x02 \x01(\x0b\x32\x16.migrationpb.LogObject\x12-\n\rto_log_object\x18\x03 \x01(\x0b\x32\x16.migrationpb.LogObject\x12/\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x1b.migrationpb.MigrationErrorH\x00\x88\x01\x01\x42\x08\n\x06_error\"b\n\x0eMigrationError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x31\n\x06\x65rrors\x18\x03 \x03(\x0b\x32!.migrationpb.MigrationErrorDetail\"G\n\x14MigrationErrorDetail\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2E\n\x07Service\x12:\n\x07Migrate\x12\x14.migrationpb.Request\x1a\x15.migrationpb.Response\"\x00(\x01\x42$Z\"pkg/services/estafette/migrationpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'migrate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"pkg/services/estafette/migrationpb'
  _LOGOBJECT._serialized_start=30
  _LOGOBJECT._serialized_end=71
  _REQUEST._serialized_start=73
  _REQUEST._serialized_end=190
  _RESPONSE._serialized_start=192
  _RESPONSE._serialized_end=263
  _MIGRATION._serialized_start=266
  _MIGRATION._serialized_end=444
  _MIGRATIONERROR._serialized_start=446
  _MIGRATIONERROR._serialized_end=544
  _MIGRATIONERRORDETAIL._serialized_start=546
  _MIGRATIONERRORDETAIL._serialized_end=617
  _SERVICE._serialized_start=619
  _SERVICE._serialized_end=688
# @@protoc_insertion_point(module_scope)
